Add project description
open-education-hub/open-education-hub-site pull request #15
Opened 2022-09-29 11:38 UTC by razvand

Add project description together with workflow diagram.

2022-09-29 13:57 UTC, lizababu requested changes

2022-09-29 13:57 UTC, lizababu commented on website/docs/description/project-description.md
> +We will thus be developing open education content (OER) and harness the benefits of the open source collaborative model to engage content consumers and content producers, thus facilitating the 5R act
```suggestion
We will thus be developing open education resources (OER) and harness the benefits of the open source collaborative model to engage content consumers and content producers, thus facilitating the 5R activities of OER: retain, reuse, revise, remix, redistribute.
```

2022-09-29 13:57 UTC, lizababu commented on website/docs/description/project-description.md
> +**Open source repositories** will make the digital content available to teachers, students and would-be contributors.
```suggestion
**Open source repositories** will make the digital content available to teachers, students / learners and would-be contributors.
```

2022-09-29 13:57 UTC, lizababu commented on website/docs/description/project-description.md
> +Students consume the digital educational content with the option of being able to contribute to it (validated by teachers) and use the automation environment when working on engaging content.
```suggestion
Students / learners consume the digital educational content with the option of being able to contribute to it (validated by teachers) and use the automation environment when working on engaging content.
```

2022-09-29 13:57 UTC, lizababu commented on website/docs/description/project-description.md
>  title: Project description
```suggestion
title: Project Description
```

2022-09-30 02:02 UTC, RazvanN7 reviewed
I would use the present form of verbs, however, that is entirely up to you. Other than that and minor edits, I think this is good to go.

2022-09-30 02:02 UTC, RazvanN7 commented on website/docs/description/project-description.md
> +**We aim to use the open source collaborative model for the development, deployment and curation of digital education content.**
```suggestion
**We aim to use the open source collaborative model for the development, deployment and curation of digital educational content.**
```

2022-09-30 02:02 UTC, RazvanN7 commented on website/docs/description/project-description.md
> +The new digital education content will be **public, customizable, dynamic, up-to-date, practical and reproducible**.
```suggestion
The new digital education content will be **public, customizable, dynamic, up-to-date, practical and reproducible**.
```
```suggestion
The new digital educational content will be **public, customizable, dynamic, up-to-date, practical and reproducible**.
```

2022-09-30 02:02 UTC, RazvanN7 commented on website/docs/description/project-description.md
> +We will thus be developing open educational resources (OER) and harness the benefits of the open source collaborative model to engage content consumers and content producers, thus facilitating the 5R
```suggestion
We are developing open educational resources (OER) and we harness the benefits of the open source collaborative model to engage content consumers and content producers, thus facilitating the 5R activities of OER: retain, reuse, revise, remix, redistribute.
```

2022-09-30 02:02 UTC, RazvanN7 commented on website/docs/description/project-description.md
> +The common open source components, methods and definitions will be adapted to the development, deployment and curation of digital education content.
```suggestion
The common open source components, methods and definitions are adapted to the development, deployment and curation of digital education content.
```

2022-09-30 02:02 UTC, RazvanN7 commented on website/docs/description/project-description.md
> +**Open source repositories** will make the digital content available to teachers, students / learners and would-be contributors.
```suggestion
**Open source repositories** make the digital content available to teachers, students / learners and would-be contributors.
```

2022-09-30 02:02 UTC, RazvanN7 commented on website/docs/description/project-description.md
> +**Open source deployment and automation solutions** will make the content practical and reproducible.
```suggestion
**Open source deployment and automation solutions** makes the content practical and reproducible.
```

2022-09-30 02:02 UTC, RazvanN7 commented on website/docs/description/project-description.md
> +Students / Learners consume the digital educational content with the option of being able to contribute to it (validated by teachers) and use the automation environment when working on engaging conte
```suggestion
Students / Learners consume the digital educational content with the option of being able to contribute to it.
Their contributions are validated by teachers and tested by the automation environment.
```

2022-10-17 07:46 UTC, lizababu approved these changes
LGTM

2022-10-17 08:14 UTC, teodutu approved these changes
The description can also do fine without the link to the 5Rs I mentioned. Still, I think it would be better with the link.

2022-10-17 08:14 UTC, teodutu commented on website/docs/description/project-description.md
> +In this way, we are facilitating the 5R activities of OER: retain, reuse, revise, remix, redistribute.
Add [a link](https://nsufl.libguides.com/oer/5rs) that explains the 5R's. Otherwise, they seem a little vague.

2022-10-17 09:32 UTC, merged