community: Add bio for Răzvan Deaconescu
open-education-hub/open-education-hub-site pull request #2
Opened 2022-07-06 14:53 UTC by razvand

Add bio and picture for Răzvan Deaconescu

2022-07-09 15:58 UTC, teodutu requested changes
You made a few typos.

2022-07-09 15:58 UTC, teodutu commented on website/docs/community/people.md
> +He supervises project activities and is engaged in content development for the [Operating Systems class](https://github.com/systems-cs-pub-ro/operating-systems-oer/) and the [Security Summer Schoo](h
```suggestion
He supervises project activities and is engaged in content development for the [Operating Systems class](https://github.com/systems-cs-pub-ro/operating-systems-oer/) and the [Security Summer School](https://github.com/security-summer-school/).
```

2022-07-09 15:58 UTC, teodutu commented on website/docs/community/people.md
> +Răzvan is an Associate Professor at University POLITEHNICA of Bucharest, Romania, the Computer Science and Engineering Department.
```suggestion
Răzvan is an Associate Professor at the University POLITEHNICA of Bucharest, Romania, the Computer Science and Engineering Department.
```

2022-07-20 13:26 UTC, lizababu approved these changes
LGTM

2022-07-20 13:26 UTC, lizababu commented on website/docs/community/people.md
> +Răzvan is an Associate Professor at University POLITEHNICA of Bucharest, Romania, the Computer Science and Engineering Department.
I'd say it's correct without `the`.

2022-07-29 13:22 UTC, teodutu approved these changes
👍

2022-08-03 15:32 UTC, lizababu approved these changes
Nice pic!

2022-08-24 16:14 UTC, merged