M4: add slides for methodology
open-education-hub/open-education-hub-site pull request #51
Opened 2023-09-12 12:46 UTC by RazvanN7

2023-09-12 13:01 UTC, razvand requested changes

2023-09-12 13:01 UTC, razvand commented on website/docs/events/m4-slides/.slides/methodology.md
> +- Github for storing content
I would replace them with logos.

2023-09-12 13:01 UTC, razvand commented on website/docs/events/m4-slides/.slides/methodology.md
> +- reading
Replace them with pics, logos, such as those here: https://icons8.com/

2023-09-12 13:01 UTC, razvand commented on website/docs/events/m4-slides/.slides/methodology.md
> +
I would add a slide named "Scope" or "Questions Answered". And add to the slides the questions that the methodology provides answers too. This is very useful to hook the audience, as these are likely questions they are asking themselves.

2023-09-12 13:01 UTC, razvand commented on website/docs/events/m4-slides/.slides/methodology.md
> +
Before you venture into internals of content, storing, types, I would go two higher level use cases.

1. **Use content**: I am an educator, I am assigned to deliver a class, I want to have a repository set with all I need. Methodology: OK, here's what you do: fork repository, configure, add logistics info, deploy, use automation, mentor student, ask student to contribute.
1. **Develop content**: I am an educator, I want to develop or port a new class. I want to create content that I, and others will use. Probably no "I" but "we" - multiple educators develop said content. Methodology: OK, here's what you do: fork oer-template, start developing content according to content types, look at existing content, build along the way, use linters, verify, ask for compliance with OpenEdu guidelines, have it hosted in OpenEdu, with credits given to you. Profit.

2023-09-12 13:01 UTC, razvand commented on website/docs/events/m4-slides/.slides/methodology.md
> +- types of content
Add a diagram in draw.io that lists all of these items interconnected.

2023-09-12 13:01 UTC, razvand commented on website/docs/events/m4-slides/.slides/methodology.md
Add a section called "Challenges and Road Ahead" or something along that way. Mention things we are unsure of, and items we want / need to tackle in the future for the methodology.

2023-09-12 14:42 UTC, RazvanN7 commented on website/docs/events/m4-slides/.slides/methodology.md
> +
I have a narrative where this is explained, but it's not explicit on the slides.

2023-09-13 05:47 UTC, razvand approved these changes

2023-09-13 05:47 UTC, merged