Added Hulda and Eggert bios
open-education-hub/open-education-hub-site pull request #8
Opened 2022-08-02 15:44 UTC by eggertkarl

Added Hulda and Eggert bios + pictures

2022-08-03 14:20 UTC, lizababu commented on website/docs/community/people.md
> +
```suggestion
```

2022-08-03 14:21 UTC, lizababu reviewed
Just small comments :D

2022-08-03 14:21 UTC, lizababu commented on website/docs/community/people.md
> +I teach various mathematics courses at the University of Iceland, in either main or assitant roles. These are usually calculus courses, though they can also included topics in complex analysis, parti
```suggestion
I teach various mathematics courses at the University of Iceland, in either main or assistant roles. These are usually Calculus courses, though they can also included topics in Complex Analysis, Partial Differential Equations, Numerical Analysis and more.
```

2022-08-03 14:23 UTC, lizababu commented on website/docs/community/people.md
> +I work full time as a math teacher at the Commercial College of Iceland and as a part time teacher at the University of Iceland. I particularly enjoy teaching calculus, probability and statistics but
```suggestion
I work full time as a math teacher at the Commercial College of Iceland and as a part time teacher at the University of Iceland. I particularly enjoy teaching Calculus, Probability and Statistics, but I am also interested in the field of Combinatorics.
```

2022-08-03 14:35 UTC, razvand requested changes
Thanks, @eggertkarl . I made some minor suggestions.

Please use one sentence on one line. This will make reviews and updates easier. Diffs are line-centric and it helps to have one sentence on one line.

Also, please create two commits for this PR: one commit adds info about yourself and another one about Hulda. It's good practice to have one commit do one thing. [This](https://www.atlassian.com/git/tutorials/rewriting-history) is a very nice tutorial on editing commits.

2022-08-03 14:35 UTC, razvand commented on website/docs/community/people.md
> +![Eggert Karl Hafsteinsson](../../static/img/people/eggert.png)
Serial killer pic ... DONE

2022-08-03 14:35 UTC, razvand commented on website/docs/community/people.md
> +I'm Hulda. I have a Bachelors degree in Mathematics and Mathematical Education and a Masters degree in Upper Secondary Education of Mathematics. My role in the OpenEdu project is to review the conten
```suggestion
I'm Hulda.
I have a Bachelors degree in Mathematics and Mathematical Education and a Masters degree in Upper Secondary Education of Mathematics.
My role in the OpenEdu project is to review the content of the Computing and Calculus for Applied Statistics (CCAS) course at the University of Iceland and adapt it to the new system developed by Open Education Hub.
```

2022-08-03 14:35 UTC, razvand commented on website/docs/community/people.md
> +I work full time as a math teacher at the Commercial College of Iceland and as a part time teacher at the University of Iceland. I particularly enjoy teaching Calculus, Probability and Statistics, bu
```suggestion
I work full time as a math teacher at the Commercial College of Iceland and as a part time teacher at the University of Iceland.
I particularly enjoy teaching Calculus, Probability and Statistics, but I am also interested in the field of Combinatorics.
```

2022-08-03 14:35 UTC, razvand commented on website/docs/community/people.md
> +
Remove extra blank line.

2022-08-03 14:35 UTC, razvand commented on website/docs/community/people.md
> +My name is Eggert Karl. I'm a math educator. I have a Masters degree in Mathematics (Multivariate Complex Analysis), Bachelors degrees in Applied Mathematics as well as Computer Science and have an a
```suggestion
My name is Eggert Karl.
I'm a math educator.
I have a Masters degree in Mathematics (Multivariate Complex Analysis), Bachelors degrees in Applied Mathematics as well as Computer Science and have an additional diploma in Upper Secondary School Education.
My work in the OpenEdu project consists mainly of adapting content developed for the Computing and Calculus for Applied Statistics (CCAS) course at the University of Iceland for the new framework that we are developing.
In addition, I also participate in development discussion, where I try to bring an educator's point of view, as well as how we can leverage past experiments, such as [tutor-web](https://tutor-web.net/).
```

2022-08-03 14:35 UTC, razvand commented on website/docs/community/people.md
> +I teach various mathematics courses at the University of Iceland, in either main or assistant roles. These are usually Calculus courses, though they can also included topics in Complex Analysis, Part
```suggestion
I teach various Mathematics courses at the University of Iceland, in either main or assistant roles.
These are usually Calculus courses, though they can also included topics in Complex Analysis, Partial Differential Equations, Numerical Analysis and more.
```

2022-08-03 15:23 UTC, eggertkarl commented
@razvand So, I read the tutorial and was trying to rebase, but it kept opening up an editor and wasn't interactive, as I thought it was supposed to be. I ended up backing up my changes, hard resetting the HEAD back to when I forked (found with reflog), then redoing my changes in two passes, making sure to commit between passes so the first commit is only adding Hulda's bio+picture, then the second pass is adding my bio+picture. 

The only other commit is something that Liza did and I seem to have accepted (though, I don't actually remember doing that...). Is the final result good enough now, or are there more things I can do?

2022-08-18 09:40 UTC, RazvanN7 reviewed
Some minor typo corrections.

2022-08-18 09:40 UTC, RazvanN7 commented on website/docs/community/people.md
> +In addition, I also participate in development discussion, where I try to bring an educator's point of view, as well as how we can leverage past experiments, such as [tutor-web](https://tutor-web.net
```suggestion
In addition, I also participate in development discussions, where I try to bring an educator's point of view, as well as how we can leverage past experiments, such as [tutor-web](https://tutor-web.net/).
```

2022-08-18 09:40 UTC, RazvanN7 commented on website/docs/community/people.md
> +These are usually Calculus courses, though they can also included topics in Complex Analysis, Partial Differential Equations, Numerical Analysis and more.
```suggestion
These are usually Calculus courses, though they can also include topics in Complex Analysis, Partial Differential Equations, Numerical Analysis and more.
```

2022-08-18 10:02 UTC, closed without merging